import { LegalDocument } from '@/components';
import { LEGAL_VERSION, OPERATOR_NAME } from '@/lib/legal';
export default function PrivacyScreen() {
  return <LegalDocument title="Privacy Policy" lastUpdated={LEGAL_VERSION} webUrl={null} sections={[
    { heading: 'About this policy', body: `${OPERATOR_NAME} provides Rankr, a personal media-ranking and social app, initially offered in the United States. This policy describes the information used by the app and website.` },
    { heading: 'Information you provide', body: 'Creating an email account requires an email address, password, and username. Google sign-in supplies account information authorized through Google, such as email, name, and profile image. Display name, biography, avatar, notes, photos, posts, and social activity are optional. We store the lists, comparisons, rankings, follows, likes, comments, reports, and feedback you choose to create. We record the terms version acknowledged during email signup. Do not include sensitive personal information in public content or feedback.' },
    { heading: 'Why we use information', body: 'We use account information to authenticate you and recover your account; your saved content to maintain rankings, display lists, and generate recommendations; social activity to provide feeds and notifications; and reports and feedback to respond to problems and protect the service. We do not require a phone number, street address, contacts access, or precise location to rank media.' },
    { heading: 'Public and private content', body: 'Your username and profile can be visible to other users. List and post visibility controls determine who can read that content in the app. Public content can be copied or shared by its viewers. Uploaded photos currently use public storage URLs: anyone with a photo URL can access that image, including images attached to private content. Do not upload confidential photos. A private list does not make its uploaded image URL private.' },
    { heading: 'Service providers and external requests', body: 'Supabase processes authentication, database records, and uploaded images. The hosting provider serves the website. Searches request metadata from providers including TMDB, RAWG, Apple iTunes, and Google Books. Images may load directly from those providers. They receive the network information needed to respond, such as your IP address and requested resource; search providers also receive search terms. Google handles Google sign-in. Native push notifications use Expo if device permission is granted. These providers process information under their own terms and privacy notices.' },
    { heading: 'Cookies, diagnostics, and tracking', body: 'Browser storage keeps you signed in. The landing ranking demo runs in memory. Guest starter lists use unencrypted local storage on your browser for up to 7 days after your last edit, so you can continue through sign-in. They are sent to your account only when you confirm saving; the local copy is then removed. You can discard a guest draft or clear site storage. Avoid sensitive information in device drafts. This version does not include advertising trackers, third-party analytics, session replay, or automatic external crash reporting. Providers may keep operational access and security logs. Sending feedback is your choice; technical error details are excluded unless you explicitly include them. See the Cookie Policy for storage purposes and controls. We do not sell personal information or share it for cross-context behavioral advertising. Do Not Track and Global Privacy Control signals do not change this no-advertising behavior.' },
    { heading: 'Retention and deletion', body: 'Account information and saved content are kept while needed to provide your account. You can remove content or request account deletion in Profile settings. Account deletion depends on the server-side deletion service. Uploaded files, reports, provider logs, and backups may require separate cleanup or expire under provider retention settings; do not assume they disappear instantly. We retain information only when needed for the service, security, resolving disputes, or legal obligations. Contact us if deletion fails or you need help removing an uploaded image.' },
    { heading: 'Your choices and requests', body: 'Edit your profile and list visibility in the app. Profile settings includes a JSON export of profile, lists, ranked items, posts, and follows; that export does not currently cover every category of information. You may request access, correction, a fuller copy, or deletion using the contact option below. We may need to verify account ownership before fulfilling a request. Rights depend on applicable law. You can disable notifications in device settings and sign out or clear site storage on a shared device.' },
    { heading: 'Children and changes', body: 'Rankr is intended for people age 13 and older, not children under 13. If you believe a child under 13 has provided personal information, contact us so we can investigate and remove it as appropriate. We update the date above when this policy changes and will provide additional notice when required by law.' },
  ]} />;
}
