import { LegalDocument } from '@/components';
import { LEGAL_VERSION, OPERATOR_NAME } from '@/lib/legal';
export default function TermsScreen() {
  return <LegalDocument title="Terms & Conditions" lastUpdated={LEGAL_VERSION} webUrl={null} sections={[
    { heading: 'Using Rankr', body: `These terms govern your use of Rankr, provided by ${OPERATOR_NAME}. By creating an account or using the service, you agree to these terms. If you do not agree, do not create an account or use the service. Our Privacy Policy explains how information is handled; acknowledging it is not permission for optional marketing or tracking.` },
    { heading: 'Eligibility and accounts', body: 'You must be at least 13 years old. If you are below the age of majority where you live, use Rankr only with a parent or guardian’s permission. Provide accurate account information, protect your password, and do not impersonate others. You are responsible for activity you authorize through your account. Contact us if you suspect unauthorized access.' },
    { heading: 'Your content and visibility', body: 'You retain ownership of your original content. You give Rankr a non-exclusive license to store, process, and display that content as needed to provide the features and visibility you select. This license does not transfer ownership. You must have the rights necessary to upload what you share. Public content can be seen and copied by others. Uploaded image URLs are currently public even when associated text is private; do not upload confidential images.' },
    { heading: 'Community rules', body: 'Do not harass, threaten, impersonate, spam, post illegal content, exploit children, or infringe privacy or intellectual property rights. Do not attempt to access other people’s private data, bypass access controls, or disrupt the service. Use reporting and blocking tools for unwanted interactions. Reports may lead to content removal or account restrictions.' },
    { heading: 'Media and recommendations', body: 'Rankr organizes opinions and metadata; it does not provide ownership of, or access to, the underlying songs, films, games, television programs, or books. Artwork and metadata belong to their respective owners and providers. Rankings and recommendations are subjective and may contain errors. External services operate under their own terms.' },
    { heading: 'Availability and changes', body: 'Rankr is a developing side project. Features may change, fail, or become unavailable. Keep a copy of content that matters to you. Where permitted by applicable law, the service is provided as available and without warranties of uninterrupted availability or accuracy. Nothing in these terms excludes rights or liability that cannot legally be excluded.' },
    { heading: 'Ending use and resolving issues', body: 'You can stop using Rankr at any time and request account deletion in Profile settings. We may restrict access to address violations, security risks, or legal requirements. Contact us to question a restriction, report infringement, or resolve a problem. Removal and retention are described in the Privacy Policy.' },
    { heading: 'Updates and contact', body: 'The date above identifies this version. We will provide notice of significant changes where required by law. Contact the operator using the option below with questions about these terms.' },
  ]} />;
}
